#!/usr/bin/env bash
#
# Script name: dmconf
# Description: Choose from a list of configuration files to edit.
# Dependencies: dmenu
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# Contributors: Derek Taylor

# Defining the text editor to use.
# DMENUEDITOR="vim"
# DMENUEDITOR="leafpad"
DMEDITOR="tilix -e nvim"

# An array of options to choose.
# You can edit this list to add/remove config files.
declare -a options=(

    "1) awesome - $HOME/.config/awesome/rc.lua"
    "2) alacritty - $HOME/.config/alacritty/alacritty.yml"
    "3) zsh - $HOME/.zshrc"
    "4) bash - $HOME/.bashrc"
    "5) neovim - $HOME/.config/nvim/init.vim"
    "6) picom - $HOME/.config/picom/picom.conf"
    "7) rofi-files - $HOME/.config/scripts/rofi/rofi-files"
    "8) theme awesome - /usr/share/awesome/themes/Nord/theme.lua"
    "quit"
)

# Piping the above array into dmenu.
# We use "printf '%s\n'" to format the array one item to a line.
choice=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i  20 -p ' Editar ')

# What to do when/if we choose 'quit'.
if [[ "$choice" == "quit" ]]; then
    echo "Program terminated." && exit 1

# What to do when/if we choose a file to edit.
elif [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	$DMEDITOR "$cfg"

# What to do if we just escape without choosing anything.
else
    echo "Program terminated." && exit 1
fi
